### ISSUE TITLE
getting playlist from minidlna

### ISSUE THREAD

**Issue by wdehoog** [medoc92/libupnpp#16]
Hi,

When I browse my minidlna server with a libupnpp program (for example upplay or my own app). The playlist files (m3u) do not show up. 

Minidlna seems to parse them and show them as directories when they refer to local files but when they contain internet streams these directories are empty and readDir() returns an error.

Is there a way to query minidlna to return the m3u files as items or another way of getting the stream url's they contain?

**Comment by medoc92** [comment]
I'm not too surprised that playlists don't work as they should as I've never really worked with them. I need to test this and compare to how it works with e.g. bubble. However, I will need some time to get to it (long queue), so if you want to give it a better look, don't hesitate :)

**Comment by wdehoog** [comment]
Well I was hoping to tap your extensive knowledge of upnp. It could help me understand if what I am looking for is even possible. 

I could not find if a Content server is supposed to offer 'normal' retrieval of any file present at the server. If minidlna does not show m3u files is this normal? Does another server, for example minimserver, do show them? And if it is possible should readDir fetch them?

**Comment by medoc92** [comment]
Well my knowledge is not that extensive :)

I've never really looked into playlists, because I mostly don't use any. If you have a bit of time to spare, and can take a look at how the different servers handle them, then having a look at what a reference CP like bubble does with them, it would be very useful.

**Comment by medoc92** [comment]
I had another look at this. I don't think that any media server actually report playlist items to the control points: they present them as album-like containers. As far as I can see, a playlist with streams in it does not work with minidlna, but it works just fine with minimserver. For example:

````
#EXTM3U

#EXTM3U
#EXTINF:-1,France Musique Classique Easy
http://direct.francemusique.fr/live/francemusiqueeasyclassique-hifi.mp3

#EXTM3U
#EXTINF:-1,France Musique Classique Plus
http://direct.francemusique.fr/live/francemusiqueclassiqueplus-hifi.mp3

#EXTM3U
#EXTINF:-1,France Musique Concerts Radio France
http://direct.francemusique.fr/live/francemusiqueconcertsradiofrance-hifi.mp3
````

With minim, the playlists appear both at their place in the folder hierarchy (as subfolders), and in the 'Playlists' top level section.

I did not try very hard with minidlna as I find it too limited compared to minim anyway, so maybe there is a way to make this work (it does support playlists for local files).

I think that the Playlist object items described in the UPnP Content Directory spec were never really thought through, as I have no idea what the entries in these should look like (object ids?). So it seems very probable that *all* content directory servers (until proven otherwise) return playlists as container object (seen as folders in the user interface). As such it's not obvious to me that libupnpp currently needs any change related to this, and I'm closing the issue. Do feel free to reopen if you get more data.
