### ISSUE TITLE
The ret always return -101

### ISSUE THREAD

**Issue by Manuel4131** [medoc92/libupnpp#2]
The return value in this instruction always return -101, complaining about the "Action Failed: setAVTransportURI()". 
   int ret = callit->second(sc, dt);

Also, I have an another question, what exactly does callit->second mean? I can't find who uses the function object and why the overriding function would return an int value. It's a strange design.  May I ask what specification do you really follow? Thanks.

**Comment by medoc92** [comment]
The return code comes from libupnp. -101 is UPNP_E_INVALID_PARAM, so I'd have to know a lot more about what you are doing before I can answer the first part. Does this happen while running upplay?

The actions are stored in an unordered_map indexed by action name. The iterator in this kind of container is a pair<string, func>, returned by the find() call. 

Here it's named 'callit', maybe not the best var name ever. callit->first is the action name, callit->second is the action function, which we call to perform the requested operation. 

I'm not too sure what you find strange in there, it's just a function array indexed by strings.

I don't know that I should be following a spec, but I guess that if any, this would be something like c++98 with some prudent inroads into c++0x. Because of builds on embedded platforms with older compilers, I get people yelling with build errors every time I try to use a new feature, 'auto' had to go away the last time...

**Comment by Manuel4131** [comment]
Sorry, I find the error occurs to the the variable setnext in the setNextAVTransportURI.
The variable setnext is true, but sc doesn't have that key.

**Comment by medoc92** [comment]
The name of the UPnP variable is "NextURI"

Are you working with upmpdcli code ? the setnext variable is just a bound value so that the same callback can be used for setavtransport and setnextavtransport. setnext is set or not while setting up the callback table inside the UpMpdAVTransport() constructor.

Maybe  knowing a bit more about what you are doing would help me to help you :)
